blank_issues_enabled: false
contact_links:
  - name: Discord Community Support
    url: https://discord.gg/bcV6TN2k9V
    about: You can also ask our Discord Community for help
  - name: Security Vulnerability
    url: https://github.com/lazybytez/.github/blob/main/docs/SECURITY.md
    about: Please report security vulnerabilities via email to security@lazybytez.de — do not open a public issue.
